class Words
  def self.random
    list.sample
  end

  def self.random_list(number_for_words = 6)
    list.sample(number_for_words)
  end

  # Return a random list of words that the user has not translated yet
  def self.new_list_for(user)
    translated_ids = user.translations.pluck(:id)
    list.select { |word| !translated_ids.include?(word[:id]) }.sample(6)
  end

  def self.translated_by(user)
    translated_ids = user.translations.pluck(:id)
    arr = list.select { |word| translated_ids.include?(word[:id]) }
    arr.map { |word| word.except(:translated) } 
  end

  def self.list
    [{
      id: 1,
      e: 'car',
      s: ['auto', 'carro', 'coche'],
      translated: false,
    },
    {
      id: 2,
      e: 'phone',
      s: ['móvil', 'celular', 'teléfono'],
      translated: false,
    },
    {
      id: 3,
      e: 'computer',
      s: ['computadora', 'computador', 'ordenador'],
      translated: false,
    },
    {
      id: 4,
      e: 'shoe',
      s: ['zapato', 'calzado', 'zapatos', 'zapatilla', 'botín', 'bota'],
      translated: false,
    },
    {
      id: 5,
      e: 'friend',
      s: ['amigo', 'amiga'],
      translated: false,
    },
    {
      id: 6,
      e: 'carpet',
      s: ['alfombra', 'moqueta', 'tapiz', 'tapete'],
      translated: false,
    },
    {
      id: 7,
      e: 'hair comb',
      s: ['peine'],
      translated: false,
    },
    {
      id: 8,
      e: 'chair',
      s: ['silla', 'sillón', 'asiento'],
      translated: false,
    },
    {
      id: 9,
      e: 'magazine',
      s: ['revista'],
      translated: false,
    },
    {
      id: 10,
      e: 'trousers',
      s: ['pantalón', 'pantalones'],
      translated: false,
    },
    {
      id: 11,
      e: 'eyelash',
      s: ['pestaña', 'pestañas'],
      translated: false,
    },
    {
      id: 12,
      e: 'keyboard',
      s: ['teclado'],
      translated: false,
    },
    {
      id: 13,
      e: 'comedy',
      s: ['comedia'],
      translated: false,
    },
    {
      id: 14,
      e: 'socks',
      s: ['medias', 'media', 'calcetines', 'calcetas'],
      translated: false,
    },
    {
      id: 15,
      e: 'tower',
      s: ['torre'],
      translated: false,
    },
    {
      id: 16,
      e: 'rabbit',
      s: ['conejo', 'coneja'],
      translated: false,
    },
    {
      id: 17,
      e: 'wig',
      s: ['peluca', 'peluquín'],
      translated: false,
    },
    {
      id: 18,
      e: 'table',
      s: ['mesa', 'tabla', 'cuadro', 'tablero'],
      translated: false,
    },
    {
      id: 19,
      e: 'window',
      s: ['ventana', 'ventanilla'],
      translated: false,
    },
    {
      id: 20,
      e: 'door',
      s: ['puerta', 'portón', 'portezuela'],
      translated: false,
    },
    {
      id: 21,
      e: 'shirt',
      s: ['camisa', 'camiseta', 'blusa', 'playera'],
      translated: false,
    },
    {
      id: 22,
      e: 'sofa',
      s: ['sofá'],
      translated: false,
    },
    {
      id: 23,
      e: 'book',
      s: ['libro', 'talonario', 'librillo', 'cartilla'],
      translated: false,
    },
    {
      id: 24,
      e: 'newspaper',
      s: ['periódico', 'diario'],
      translated: false,
    },
    {
      id: 25,
      e: 'article',
      s: ['artículo', 'objeto', 'producto'],
      translated: false,
    },
    {
      id: 26,
      e: 'item',
      s: ['ítem', 'objeto', 'artículo'],
      translated: false,
    },
    {
      id: 27,
      e: 'issue',
      s: ['tema', 'asunto', 'problema', 'cuestión', 'emisión'],
      translated: false,
    },
    {
      id: 28,
      e: 'case',
      s: ['caso', 'caja', 'causa', 'asunto', 'estuche', 'funda', 'maletín'],
      translated: false,
    },
    {
      id: 29,
      e: 'subject',
      s: ['sujeto', 'tema', 'asunto', 'asignatura'],
      translated: false,
    },
    {
      id: 30,
      e: 'topic',
      s: ['tema', 'asunto'],
      translated: false,
    },
    {
      id: 31,
      e: 'thing',
      s: ['cosa', 'objeto', 'cuestión', 'asunto'],
      translated: false,
    },
    {
      id: 32,
      e: 'help',
      s: ['ayuda'],
      translated: false,
    },
    {
      id: 33,
      e: 'bear',
      s: ['oso', 'osa'],
      translated: false,
    },
    {
      id: 34,
      e: 'peach',
      s: ['durazno', 'melocotón'],
      translated: false,
    },
    {
      id: 35,
      e: 'passion fruit',
      s: ['maracuyá', 'granadilla', 'parcha', 'curuba', 'parchita'],
      translated: false,
    },
    {
      id: 36,
      e: 'apple',
      s: ['manzana'],
      translated: false,
    },
    {
      id: 37,
      e: 'watermelon',
      s: ['sandía', 'patilla'],
      translated: false,
    },
    {
      id: 38,
      e: 'strawberry',
      s: ['fresa', 'frutilla', 'fresón'],
      translated: false,
    },
    {
      id: 39,
      e: 'pear',
      s: ['pera'],
      translated: false,
    },
    {
      id: 40,
      e: 'fork',
      s: ['tenedor', 'horquilla', 'bifurcación'],
      translated: false,
    },
    {
      id: 41,
      e: 'spoon',
      s: ['cuchara', 'cucharilla'],
      translated: false,
    },
    {
      id: 42,
      e: 'knife',
      s: ['cuchillo', 'cuchilla', 'navaja'],
      translated: false,
    },
    {
      id: 43,
      e: 'equation',
      s: ['ecuación'],
      translated: false,
    },
    {
      id: 44,
      e: 'team',
      s: ['equipo', 'grupo', 'yunta'],
      translated: false,
    },
    {
      id: 45,
      e: 'browser',
      s: ['navegador', 'navegadora', 'explorador'],
      translated: false,
    },
    {
      id: 46,
      e: 'website',
      s: ['sitio web', 'página web'],
      translated: false,
    },
    {
      id: 47,
      e: 'page',
      s: ['página', 'hoja', 'paje'],
      translated: false,
    },
    {
      id: 48,
      e: 'sword',
      s: ['espada'],
      translated: false,
    },
    {
      id: 49,
      e: 'shield',
      s: ['escudo', 'blindaje', 'protección'],
      translated: false,
    },
    {
      id: 50,
      e: 'brightness',
      s: ['brillo', 'luminosidad', 'claridad'],
      translated: false,
    },
    {
      id: 51,
      e: 'shine',
      s: ['brillo', 'resplandor'],
      translated: false,
    },
    {
      id: 52,
      e: 'player',
      s: ['jugador', 'jugadora', 'reproductor'],
      translated: false,
    },
    {
      id: 53,
      e: 'path',
      s: ['camino', 'sendero', 'trayectoria', 'ruta', 'recorrido', 'paso', 'curso', 'vía'],
      translated: false,
    },
    {
      id: 54,
      e: 'silk',
      s: ['seda'],
      translated: false,
    },
    {
      id: 55,
      e: 'wood',
      s: ['madera', 'leña', 'bosque', 'leño'],
      translated: false,
    },
    {
      id: 56,
      e: 'forest',
      s: ['bosque', 'selva'],
      translated: false,
    },
    {
      id: 57,
      e: 'paradise',
      s: ['paraíso'],
      translated: false,
    },
    {
      id: 58,
      e: 'bull',
      s: ['toro'],
      translated: false,
    },
    {
      id: 59,
      e: 'beer',
      s: ['cerveza'],
      translated: false,
    },
    {
      id: 60,
      e: 'bear',
      s: ['oso', 'osa'],
      translated: false,
    },
    {
      id: 61,
      e: 'lamp',
      s: ['lámpara', 'bombilla'],
      translated: false,
    },
    {
      id: 62,
      e: 'lantern',
      s: ['linterna', 'farol'],
      translated: false,
    },
    {
      id: 63,
      e: 'tablet',
      s: ['tableta', 'comprimido', 'pastilla', 'tabla'],
      translated: false,
    },
    {
      id: 64,
      e: 'screen',
      s: ['pantalla', 'rejilla', 'cortina'],
      translated: false,
    },
    {
      id: 65,
      e: 'trouble',
      s: ['problema', 'apuro', 'dificultad', 'molestia', 'angustia', 'pena', 'lío', 'preocupación', 'aprieto'],
      translated: false,
    },
    {
      id: 66,
      e: 'rainbow',
      s: ['arcoíris', 'arco iris'],
      translated: false,
    },
    {
      id: 67,
      e: 'medal',
      s: ['medalla', 'condecoración'],
      translated: false,
    },
    {
      id: 68,
      e: 'happiness',
      s: ['felicidad', 'alegría', 'dicha'],
      translated: false,
    },
    {
      id: 69,
      e: 'night',
      s: ['noche'],
      translated: false,
    },
    {
      id: 70,
      e: 'day',
      s: ['día'],
      translated: false,
    },
    {
      id: 71,
      e: 'soap',
      s: ['jabón'],
      translated: false,
    },
    {
      id: 72,
      e: 'wind',
      s: ['viento', 'aire'],
      translated: false,
    },
    {
      id: 73,
      e: 'breath',
      s: ['aliento', 'respiración', 'respiro'],
      translated: false,
    },
    {
      id: 74,
      e: 'sigh',
      s: ['suspiro'],
      translated: false,
    },
    {
      id: 75,
      e: 'whisper',
      s: ['susurro', 'cuchicheo', 'rumor'],
      translated: false,
    },
    {
      id: 76,
      e: 'reflection',
      s: ['reflejo', 'reflexión', 'pensamiento'],
      translated: false,
    },
    {
      id: 77,
      e: 'mirror',
      s: ['espejo'],
      translated: false,
    },
    {
      id: 78,
      e: 'bite',
      s: ['mordida', 'mordedura', 'bocado', 'picadura', 'mordisco'],
      translated: false,
    },
    {
      id: 79,
      e: 'sign',
      s: ['señal', 'signo', 'muestra', 'seña', 'cartel', 'letrero', 'rastro'],
      translated: false,
    },
    {
      id: 80,
      e: 'chest',
      s: ['cofre', 'pecho', 'cómoda'],
      translated: false,
    },
    {
      id: 81,
      e: 'thought',
      s: ['pensamiento', 'idea', 'reflexión'],
      translated: false,
    },
    {
      id: 82,
      e: 'hug',
      s: ['abrazo'],
      translated: false,
    },
    {
      id: 83,
      e: 'discomfort',
      s: ['molestia', 'incomodidad', 'malestar', 'inquietud'],
      translated: false,
    },
    {
      id: 84,
      e: 'theory',
      s: ['teoría'],
      translated: false,
    },
    {
      id: 85,
      e: 'button',
      s: ['botón', 'pulsador', 'interruptor', 'tecla'],
      translated: false,
    },
    {
      id: 86,
      e: 'letter',
      s: ['carta', 'letra'],
      translated: false,
    },
    {
      id: 87,
      e: 'document',
      s: ['documento', 'paper', 'file'],
      translated: false,
    },
    {
      id: 88,
      e: 'record',
      s: ['registro', 'récord', 'expediente', 'disco', 'historial', 'acta', 'antecedentes', 'grabacion'],
      translated: false,
    },
    {
      id: 89,
      e: 'life',
      s: ['vida', 'duración'],
      translated: false,
    },
    {
      id: 90,
      e: 'guilt',
      s: ['culpa', 'culpabilidad'],
      translated: false,
    },
    {
      id: 91,
      e: 'bottle',
      s: ['botella', 'biberón', 'envase', 'frasco'],
      translated: false,
    },
    {
      id: 92,
      e: 'painting',
      s: ['pintura', 'cuadro'],
      translated: false,
    },
    {
      id: 93,
      e: 'circle',
      s: ['círculo'],
      translated: false,
    },
    {
      id: 94,
      e: 'square',
      s: ['plaza', 'casilla', 'cuadro', 'escuadra', 'recuadro', 'cuadrado'],
      translated: false,
    },
    {
      id: 95,
      e: 'yellow',
      s: ['amarillo'],
      translated: false,
    },
    {
      id: 96,
      e: 'red',
      s: ['rojo'],
      translated: false,
    },
    {
      id: 97,
      e: 'green',
      s: ['verde'],
      translated: false,
    },
    {
      id: 98,
      e: 'sky',
      s: ['cielo'],
      translated: false,
    },
    {
      id: 99,
      e: 'heaven',
      s: ['cielo', 'paraíso'],
      translated: false,
    },
    {
      id: 100,
      e: 'drug',
      s: ['droga', 'fármaco', 'medicamento', 'medicina'],
      translated: false,
    },
    {
      id: 101,
      e: 'loneliness',
      s: ['soledad', 'aislamiento'],
      translated: false,
    },
    {
      id: 102,
      e: 'torture',
      s: ['tortura', 'tormento', 'suplicio'],
      translated: false,
    },
    {
      id: 103,
      e: 'foolishness',
      s: ['tontería', 'necedad', 'estupidez', 'idiotez', 'imprudencia', 'insensatez'],
      translated: false,
    },
    {
      id: 104,
      e: 'imprudence',
      s: ['imprudencia'],
      translated: false,
    },
    {
      id: 105,
      e: 'rudeness',
      s: ['rudeza', 'grosería'],
      translated: false,
    },
    {
      id: 106,
      e: 'icon',
      s: ['ícono', 'símbolo', 'ídolo', 'icono'],
      translated: false,
    },
    {
      id: 107,
      e: 'airplane',
      s: ['avión', 'aeroplano', 'aeronave'],
      translated: false,
    },
    {
      id: 108,
      e: 'pilot',
      s: ['piloto', 'práctico', 'guía'],
      translated: false,
    },
    {
      id: 109,
      e: 'priest',
      s: ['sacerdote', 'cura', 'clérigo', 'padre', 'pastor', 'párroco'],
      translated: false,
    },
    {
      id: 110,
      e: 'sin',
      s: ['pecado'],
      translated: false,
    },
    {
      id: 111,
      e: 'heart',
      s: ['corazón', 'centro'],
      translated: false,
    },
    {
      id: 112,
      e: 'soul',
      s: ['alma', 'espíritu'],
      translated: false,
    },
    {
      id: 113,
      e: 'guitar',
      s: ['guitarra'],
      translated: false,
    },
    {
      id: 114,
      e: 'drum',
      s: ['tambor', 'batería'],
      translated: false,
    },
    {
      id: 115,
      e: 'god',
      s: ['dios'],
      translated: false,
    },
    {
      id: 116,
      e: 'application',
      s: ['solicitud', 'aplicación', 'uso'],
      translated: false,
    },
    {
      id: 117,
      e: 'form',
      s: ['formulario', 'forma'],
      translated: false,
    },
    {
      id: 118,
      e: 'cold',
      s: ['frío', 'resfriado', 'resfrío'],
      translated: false,
    },
    {
      id: 119,
      e: 'hot',
      s: ['caliente', 'caluroso', 'cálido', 'ardiente', 'picante'],
      translated: false,
    },
    {
      id: 120,
      e: 'judgment',
      s: ['juicio', 'sentencia', 'fallo', 'criterio', 'opinión'],
      translated: false,
    },
    {
      id: 121,
      e: 'failure',
      s: ['fracaso', 'fallo', 'falla', 'avería'],
      translated: false,
    },
    {
      id: 122,
      e: 'farm',
      s: ['granja', 'hacienda', 'criadero', 'alquería'],
      translated: false,
    },
    {
      id: 123,
      e: 'ranch',
      s: ['rancho', 'hacienda', 'estancia'],
      translated: false,
    },
    {
      id: 124,
      e: 'smile',
      s: ['sonrisa', 'risa'],
      translated: false,
    },
    {
      id: 125,
      e: 'teeth',
      s: ['dientes', 'dentadura'],
      translated: false,
    },
    {
      id: 126,
      e: 'call',
      s: ['llamada', 'llamamiento', 'convocatoria'],
      translated: false,
    },
    {
      id: 127,
      e: 'ad',
      s: ['anuncio', 'aviso', 'publicidad', 'propaganda', 'comercial'],
      translated: false,
    },
    {
      id: 128,
      e: 'voice',
      s: ['voz'],
      translated: false,
    },
    {
      id: 129,
      e: 'name',
      s: ['nombre'],
      translated: false,
    },
    {
      id: 130,
      e: 'lastname',
      s: ['apellido', 'nombre de familia'],
      translated: false,
    },
    {
      id: 131,
      e: 'equality',
      s: ['igualdad', 'equidad', 'paridad'],
      translated: false,
    },
    {
      id: 132,
      e: 'constancy',
      s: ['constancia', 'perseverancia'],
      translated: false,
    },
    {
      id: 133,
      e: 'fidelity',
      s: ['fidelidad'],
      translated: false,
    },
    {
      id: 134,
      e: 'loyalty',
      s: ['lealtad'],
      translated: false,
    },
    {
      id: 135,
      e: 'picture',
      s: ['imagen', 'foto', 'cuadro', 'dibujo', 'visión', 'fotografía'],
      translated: false,
    },
    {
      id: 136,
      e: 'value',
      s: ['valor', 'precio'],
      translated: false,
    },
    {
      id: 137,
      e: 'worth',
      s: ['valor', 'valía'],
      translated: false,
    },
    {
      id: 138,
      e: 'relevance',
      s: ['relevancia', 'pertinencia', 'relación', 'importancia'],
      translated: false,
    },
    {
      id: 139,
      e: 'merit',
      s: ['mérito'],
      translated: false,
    },
    {
      id: 140,
      e: 'mountain',
      s: ['montaña', 'monte', 'cerro'],
      translated: false,
    },
    {
      id: 141,
      e: 'memory',
      s: ['memoria', 'recuerdo'],
      translated: false,
    },
    {
      id: 142,
      e: 'hate',
      s: ['odio'],
      translated: false,
    },
    {
      id: 143,
      e: 'love',
      s: ['amor'],
      translated: false,
    },
    {
      id: 144,
      e: 'translator',
      s: ['traductor'],
      translated: false,
    },
    {
      id: 145,
      e: 'interpreter',
      s: ['intérprete', 'traductor'],
      translated: false,
    },
    {
      id: 146,
      e: 'teacher',
      s: ['profesor', 'maestro', 'tutor', 'docente', 'instructor'],
      translated: false,
    },
    {
      id: 147,
      e: 'gym',
      s: ['gimnasio'],
      translated: false,
    },
    {
      id: 148,
      e: 'sport',
      s: ['deporte'],
      translated: false,
    },
    {
      id: 149,
      e: 'victim',
      s: ['víctima'],
      translated: false,
    },
    {
      id: 150,
      e: 'earth',
      s: ['tierra', 'suelo'],
      translated: false,
    },
    {
      id: 151,
      e: 'planet',
      s: ['planeta'],
      translated: false,
    },
    {
      id: 152,
      e: 'void',
      s: ['vacío', 'hueco', 'espacio', 'agujero', 'espacio'],
      translated: false,
    },
    {
      id: 153,
      e: 'chance',
      s: ['oportunidad', 'casualidad', 'azar', 'ocasión', 'posibilidad', 'suerte'],
      translated: false,
    },
    {
      id: 154,
      e: 'space',
      s: ['espacio', 'lugar', 'zona', 'sitio'],
      translated: false,
    },
    {
      id: 155,
      e: 'place',
      s: ['lugar','sitio', 'puesto', 'posición', 'plaza', 'casa'],
      translated: false,
    },
    {
      id: 156,
      e: 'room',
      s: ['habitación', 'sala', 'cuarto', 'espacio', 'pieza', 'sitio'],
      translated: false,
    },
    {
      id: 157,
      e: 'eye',
      s: ['ojo'],
      translated: false,
    },
    {
      id: 158,
      e: 'mouth',
      s: ['boca', ' desembocadura'],
      translated: false,
    },
    {
      id: 159,
      e: 'energy',
      s: ['energía', 'vigor'],
      translated: false,
    },
    {
      id: 160,
      e: 'little finger',
      s: ['meñique', 'dedo meñique', 'dedo pequeño'],
      translated: false,
    },
    {
      id: 161,
      e: 'word',
      s: ['palabra', 'término'],
      translated: false,
    },
    {
      id: 162,
      e: 'sea',
      s: ['mar'],
      translated: false,
    },
    {
      id: 163,
      e: 'ocean',
      s: ['océano'],
      translated: false,
    },
    {
      id: 164,
      e: 'air conditioner',
      s: ['aire acondicionado', 'acondicionador de aire'],
      translated: false,
    },
    {
      id: 165,
      e: 'world',
      s: ['mundo'],
      translated: false,
    },
    {
      id: 166,
      e: 'century',
      s: ['siglo'],
      translated: false,
    },
    {
      id: 167,
      e: 'question',
      s: ['pregunta', 'cuestión', 'duda', 'interrogación', 'problema'],
      translated: false,
    },
    {
      id: 168,
      e: 'witness',
      s: ['testigo', 'testimonio', 'espectador'],
      translated: false,
    },
    {
      id: 169,
      e: 'viewer',
      s: ['espectador', 'telespectador', 'televidente'],
      translated: false,
    },
    {
      id: 170,
      e: 'television',
      s: ['televisión', 'televisor'],
      translated: false,
    },
    {
      id: 171,
      e: 'band',
      s: ['banda', 'venda', 'grupo', 'cinta'],
      translated: false,
    },
    {
      id: 172,
      e: 'gang',
      s: ['banda', 'pandilla', 'cuadrilla', 'grupo'],
      translated: false,
    },
    {
      id: 173,
      e: 'soldier',
      s: ['soldado', 'militar'],
      translated: false,
    },
    {
      id: 174,
      e: 'restlessness',
      s: ['inquietud', 'intranquilidad', 'agitación'],
      translated: false,
    },
    {
      id: 175,
      e: 'peace',
      s: ['paz', 'tranquilidad'],
      translated: false,
    },
    {
      id: 176,
      e: 'justice',
      s: ['justicia'],
      translated: false,
    },
    {
      id: 177,
      e: 'evil',
      s: ['mal', 'maldad'],
      translated: false,
    },
    {
      id: 178,
      e: 'malice',
      s: ['malicia', 'maldad', 'dolo', 'malevolencia'],
      translated: false,
    },
    {
      id: 179,
      e: 'dare',
      s: ['desafío', 'atrevimiento', 'reto'],
      translated: false,
    },
    {
      id: 180,
      e: 'pain',
      s: ['dolor', 'pena', 'sufrimiento'],
      translated: false,
    },
    {
      id: 181,
      e: 'invention',
      s: ['invento', 'invención'],
      translated: false,
    },
    {
      id: 182,
      e: 'footprint',
      s: ['huella', 'pisada', 'rastro'],
      translated: false,
    },
    {
      id: 183,
      e: 'knowledge',
      s: ['conocimiento', 'conocimientos', 'saber'],
      translated: false,
    },
    {
      id: 184,
      e: 'heat',
      s: ['calor', 'calefacción'],
      translated: false,
    },
    {
      id: 185,
      e: 'wisdom',
      s: ['sabiduría', 'juicio', 'saber'],
      translated: false,
    },
    {
      id: 186,
      e: 'patience',
      s: ['paciencia'],
      translated: false,
    },
    {
      id: 187,
      e: 'absence',
      s: ['ausencia', 'falta'],
      translated: false,
    },
    {
      id: 188,
      e: 'mix',
      s: ['mezcla', 'combinación'],
      translated: false,
    },
    {
      id: 189,
      e: 'dream',
      s: ['sueño', 'ensueño', 'ideal'],
      translated: false,
    },
    {
      id: 190,
      e: 'hesitation',
      s: ['duda', 'vacilación', 'indecisión'],
      translated: false,
    }];
  end
end